<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PersonnelDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Vider la table avant d'insérer les nouvelles données
        DB::table('personnels')->delete();

        $personnel = [
            // Enseignants
            [
                'nom' => 'DIOP',
                'prenom' => 'YOUSSOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Mathématiques/Physique-Chimie',
                'statut' => 'actif',
                'date_embauche' => '2024-09-27',
                'date_fin' => null,
                'observations' => '18h/semaine - 1300 CFA/h',
            ],
            [
                'nom' => 'DIAW',
                'prenom' => 'FATOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Anglais',
                'statut' => 'actif',
                'date_embauche' => '2023-10-19',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'SOW',
                'prenom' => 'MOUHAMED',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Histoire-Géographie',
                'statut' => 'actif',
                'date_embauche' => '2008-10-18',
                'date_fin' => null,
                'observations' => '9h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'GAYE',
                'prenom' => 'MODOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Français/Histoire-Géographie',
                'statut' => 'actif',
                'date_embauche' => '2023-10-19',
                'date_fin' => null,
                'observations' => '14h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'DIENG',
                'prenom' => 'SERIGNE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Histoire-Géographie',
                'statut' => 'actif',
                'date_embauche' => '2020-11-05',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'LO',
                'prenom' => 'MOMAR',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Anglais',
                'statut' => 'actif',
                'date_embauche' => '2014-10-01',
                'date_fin' => null,
                'observations' => '16h/semaine - 1300 CFA/h',
            ],
            [
                'nom' => 'DIONGUE',
                'prenom' => 'MASSE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Français/Histoire-Géographie',
                'statut' => 'actif',
                'date_embauche' => '2023-10-03',
                'date_fin' => null,
                'observations' => '15h/semaine - 1400 CFA/h',
            ],
            [
                'nom' => 'TAMBA',
                'prenom' => 'ADAMA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Économie',
                'statut' => 'actif',
                'date_embauche' => '2018-10-01',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'THIAM',
                'prenom' => 'YOUSSOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Anglais',
                'statut' => 'actif',
                'date_embauche' => '2019-10-07',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'DIOP',
                'prenom' => 'MALICK',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Arabe',
                'statut' => 'actif',
                'date_embauche' => '2024-10-01',
                'date_fin' => null,
                'observations' => '6h/semaine - 1300 CFA/h',
            ],
            [
                'nom' => 'DIOP',
                'prenom' => 'AMADOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Italien',
                'statut' => 'actif',
                'date_embauche' => '2024-11-04',
                'date_fin' => null,
                'observations' => '3h/semaine - 2500 CFA/h',
            ],
            [
                'nom' => 'LEYE',
                'prenom' => 'IBRAHIMA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Éducation Physique et Sportive',
                'statut' => 'actif',
                'date_embauche' => '2020-10-05',
                'date_fin' => null,
                'observations' => '6h/semaine - 1300 CFA/h',
            ],
            [
                'nom' => 'SENE',
                'prenom' => 'MOUSSA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Sciences de la Vie et de la Terre',
                'statut' => 'actif',
                'date_embauche' => '2024-11-20',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'SEYE',
                'prenom' => 'TAMSIR',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Éducation Physique et Sportive',
                'statut' => 'actif',
                'date_embauche' => '2018-10-12',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h - Date embauche corrigée',
            ],
            [
                'nom' => 'NDIAYE',
                'prenom' => 'OMAR',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Philosophie',
                'statut' => 'actif',
                'date_embauche' => '2018-10-12',
                'date_fin' => null,
                'observations' => '6h/semaine - 2000 CFA/h',
            ],
            [
                'nom' => 'DIALLO FRANCO',
                'prenom' => 'MAMADOU',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Mathématiques',
                'statut' => 'actif',
                'date_embauche' => '2020-10-05',
                'date_fin' => null,
                'observations' => '6h/semaine - 1300 CFA/h',
            ],
            [
                'nom' => 'THIOUNE',
                'prenom' => 'MAMADOU LAMINE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Arabe',
                'statut' => 'actif',
                'date_embauche' => '2010-10-05',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'SOW',
                'prenom' => 'DJIBY',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Espagnol',
                'statut' => 'actif',
                'date_embauche' => '2008-10-06',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'FALL',
                'prenom' => 'AMETH HADRAME',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Mathématiques',
                'statut' => 'actif',
                'date_embauche' => '2024-11-06',
                'date_fin' => null,
                'observations' => '12h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'DIALLO CFAM',
                'prenom' => 'IBRAHIMA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Mathématiques',
                'statut' => 'actif',
                'date_embauche' => '2021-10-19',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'GUEYE',
                'prenom' => 'ISSA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Espagnol',
                'statut' => 'actif',
                'date_embauche' => '2023-11-02',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'GUEYE',
                'prenom' => 'MBACKE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Espagnol',
                'statut' => 'actif',
                'date_embauche' => '2024-10-10',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'SENE',
                'prenom' => 'SERIGNE MBACKE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Physique-Chimie',
                'statut' => 'actif',
                'date_embauche' => '2022-10-04',
                'date_fin' => null,
                'observations' => '8h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'NDIAYE',
                'prenom' => 'IBRAHIMA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Français',
                'statut' => 'actif',
                'date_embauche' => '2010-10-05',
                'date_fin' => null,
                'observations' => '20h/semaine - 2000 CFA/h - Professeur principal',
            ],
            [
                'nom' => 'TALL',
                'prenom' => 'AMINATA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Sciences de la Vie et de la Terre',
                'statut' => 'actif',
                'date_embauche' => '1991-10-08',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'SARR',
                'prenom' => 'NDIAGA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Éducation Physique et Sportive',
                'statut' => 'actif',
                'date_embauche' => '1991-10-08',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'DABO',
                'prenom' => 'CHEIKH',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Portugais',
                'statut' => 'actif',
                'date_embauche' => '1991-10-08',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'LO',
                'prenom' => 'ABDOULAYE',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Arabe',
                'statut' => 'actif',
                'date_embauche' => '2019-10-01',
                'date_fin' => null,
                'observations' => '4h/semaine - 1500 CFA/h',
            ],
            [
                'nom' => 'DIOP',
                'prenom' => 'MOUSTAPHA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'enseignant',
                'discipline' => 'Mathématiques/Physique-Chimie',
                'statut' => 'actif',
                'date_embauche' => '2019-10-01',
                'date_fin' => null,
                'observations' => '2h/semaine - 1750 CFA/h',
            ],

            // Personnel administratif
            [
                'nom' => 'NDOUR',
                'prenom' => 'ARFANG',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'directeur',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '2024-10-01',
                'date_fin' => null,
                'observations' => 'Directeur - Temps plein - 250 000 CFA/mois',
            ],

            // Secrétaires
            [
                'nom' => 'SECK',
                'prenom' => 'BINTA',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'secretaire',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '2024-10-01',
                'date_fin' => null,
                'observations' => 'Secrétaire - Temps plein - 45 000 CFA/mois',
            ],
            [
                'nom' => 'BONNE',
                'prenom' => 'MAREME',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'secretaire',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '2019-10-01',
                'date_fin' => null,
                'observations' => 'Secrétaire spécialisée Arabe - Temps plein - 30 000 CFA/mois',
            ],

            // Surveillants
            [
                'nom' => 'SYLLA',
                'prenom' => 'AMADOU DIOUF',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'surveillant',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '2015-10-15',
                'date_fin' => null,
                'observations' => 'Surveillant - Temps plein - 100 000 CFA/mois',
            ],
            [
                'nom' => 'NDIAYE',
                'prenom' => 'ABDOU AZIZ',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'surveillant',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '1991-10-08',
                'date_fin' => null,
                'observations' => 'Surveillant - Temps plein - 75 000 CFA/mois',
            ],
            [
                'nom' => 'FALL',
                'prenom' => 'MAKHTAR',
                'telephone' => null,
                'adresse' => null,
                'cni' => null,
                'type_personnel' => 'surveillant',
                'discipline' => null,
                'statut' => 'actif',
                'date_embauche' => '2015-10-01',
                'date_fin' => null,
                'observations' => 'Surveillant - Temps plein - 40 000 CFA/mois',
            ],
        ];

        foreach ($personnel as $person) {
            DB::table('personnels')->insert(array_merge($person, [
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));            
        }

        $this->command->info('Personnel data imported successfully!');
        $this->command->info('Total records inserted: ' . count($personnel));
    }
}
